import unittest

from pico_scheduler.generator import GeneratorOptions, generate_main_py


class PicoSchedulerGeneratorTests(unittest.TestCase):
    def test_gpio_only_output_omits_pwm_code(self) -> None:
        text = generate_main_py(
            controller_id="pump_n_lights",
            state={
                "report_every": 5,
                "devices": [
                    {
                        "type": "gpio",
                        "pin": 15,
                        "current_t": 0,
                        "reschedule": 1,
                        "pattern": [{"val": 1, "dur": 10}, {"val": 0, "dur": 20}],
                    }
                ],
            },
            git_version="abc1234",
            generated_at="2026-05-04T13:02:11-10:00",
            options=GeneratorOptions(),
        )
        self.assertIn('Generated by: plamp/pico-firmware/pico_scheduler_generator.py', text)
        self.assertIn('Git version: abc1234', text)
        self.assertIn('"devices": [', text)
        self.assertIn('Pin(15, Pin.OUT)', text)
        self.assertNotIn('PWM(', text)
        self.assertNotIn('from machine import Pin, PWM', text)

    def test_pwm_only_output_omits_gpio_setup(self) -> None:
        text = generate_main_py(
            controller_id="pump_n_lights",
            state={
                "report_every": 5,
                "devices": [
                    {
                        "type": "pwm",
                        "pin": 16,
                        "current_t": 0,
                        "reschedule": 1,
                        "pattern": [{"val": 1000, "dur": 10}],
                    }
                ],
            },
            git_version="abc1234",
            generated_at="2026-05-04T13:02:11-10:00",
            options=GeneratorOptions(pwm_freq=500, loop_sleep_ms=25),
        )
        self.assertIn('from machine import Pin, PWM', text)
        self.assertIn('PWM_FREQ = 500', text)
        self.assertNotIn('Pin(16, Pin.OUT)', text)

    def test_report_uses_type_not_kind_and_no_startup(self) -> None:
        text = generate_main_py(
            controller_id="pump_n_lights",
            state={"report_every": 5, "devices": []},
            git_version="abc1234",
            generated_at="2026-05-04T13:02:11-10:00",
            options=GeneratorOptions(),
        )
        self.assertIn('"type": "report"', text)
        self.assertIn('"type": "error"', text)
        self.assertNotIn('"kind"', text)
        self.assertNotIn("startup", text)
        self.assertNotIn("state.json", text)

    def test_provenance_block_includes_input_json_and_options(self) -> None:
        text = generate_main_py(
            controller_id="pump_n_lights",
            state={"report_every": 5, "devices": []},
            git_version="abc1234",
            generated_at="2026-05-04T13:02:11-10:00",
            options=GeneratorOptions(loop_sleep_ms=25, pwm_freq=700),
        )
        self.assertIn('"""', text)
        self.assertIn("Generated at: 2026-05-04T13:02:11-10:00", text)
        self.assertIn('"options": {', text)
        self.assertIn('"loop_sleep_ms": 25', text)
        self.assertIn('"pwm_freq": 700', text)

    def test_empty_devices_still_reports_devices_array(self) -> None:
        text = generate_main_py(
            controller_id="pump_n_lights",
            state={"report_every": 5, "devices": []},
            git_version="abc1234",
            generated_at="2026-05-04T13:02:11-10:00",
            options=GeneratorOptions(),
        )
        self.assertIn('"devices": out', text)
        self.assertIn("devices = []", text)
