from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path


GENERATOR_PATH = "plamp/pico-firmware/pico_scheduler_generator.py"
TEMPLATES_DIR = Path(__file__).with_name("templates")


@dataclass(frozen=True)
class GeneratorOptions:
    loop_sleep_ms: int = 20
    pwm_freq: int = 1000


def _device_var_name(index: int, device: dict) -> str:
    value = device.get("id")
    if isinstance(value, str) and value.strip():
        slug = re.sub(r"[^A-Za-z0-9_]+", "_", value.strip())
        slug = slug.strip("_")
        if slug and not slug[0].isdigit():
            return slug
    return f"device_{index}"


def _device_types(devices: list[dict]) -> set[str]:
    return {str(device.get("type")) for device in devices if isinstance(device, dict)}


def _machine_import(types: set[str]) -> str:
    if "pwm" in types:
        return "from machine import Pin, PWM"
    return "from machine import Pin"


def _device_literal(device: dict, *, include_runtime_fields: bool) -> list[str]:
    lines = ["{"]
    for key in ("id", "type", "pin", "elapsed_t", "reschedule", "pattern"):
        if key not in device:
            continue
        lines.append(f'    "{key}": {json.dumps(device[key], separators=(", ", ": "))},')
    if include_runtime_fields:
        lines.append(f'    "total_t": {sum(int(step["dur"]) for step in device["pattern"])},')
        lines.append('    "last_value": None,')
        if device["type"] == "gpio":
            lines.append(f'    "output": Pin({device["pin"]}, Pin.OUT),')
        else:
            lines.append(f'    "output": _pwm_output({device["pin"]}),')
    lines.append("}")
    return lines


def _template(name: str) -> str:
    return (TEMPLATES_DIR / name).read_text(encoding="utf-8")


def _provenance_block(
    *,
    controller_id: str,
    state: dict,
    git_version: str,
    generated_at: str,
    options: GeneratorOptions,
) -> str:
    payload = {
        "report_every": state["report_every"],
        "devices": state["devices"],
        "options": {
            "loop_sleep_ms": options.loop_sleep_ms,
            "pwm_freq": options.pwm_freq,
        },
    }
    return "\n".join(
        [
            '"""',
            f"Generated by: {GENERATOR_PATH}",
            f"Generated at: {generated_at}",
            f"Git version: {git_version}",
            f"Controller: {controller_id}",
            "Generator input:",
            json.dumps(payload, indent=2),
            '"""',
        ]
    )


def _render_device_assignments(devices: list[dict]) -> str:
    if not devices:
        return "devices = []"
    lines: list[str] = []
    names: list[str] = []
    for index, device in enumerate(devices):
        name = _device_var_name(index, device)
        names.append(name)
        template_name = "pwm_device.py.tmpl" if device["type"] == "pwm" else "gpio_device.py.tmpl"
        rendered = _template(template_name).format(
            name=name,
            id_line=f'"id": {json.dumps(device["id"])},\n    ' if "id" in device else "",
            pin=device["pin"],
            elapsed_t=device["elapsed_t"],
            reschedule=device["reschedule"],
            pattern=json.dumps(device["pattern"], separators=(", ", ": ")),
            total_t=sum(int(step["dur"]) for step in device["pattern"]),
        )
        lines.append(rendered)
        lines.append("")
    lines.append("devices = [")
    for name in names:
        lines.append(f"    {name},")
    lines.append("]")
    return "\n".join(lines)


def _render_pwm_helper(types: set[str], pwm_freq: int) -> str:
    if "pwm" not in types:
        return ""
    return "\n".join(
        [
            f"PWM_FREQ = {pwm_freq}",
            "",
            "def _pwm_output(pin):",
            "    output = PWM(Pin(pin))",
            "    output.freq(PWM_FREQ)",
            "    return output",
            "",
        ]
    )


def generate_main_py(
    *,
    controller_id: str,
    state: dict,
    git_version: str,
    generated_at: str,
    options: GeneratorOptions,
) -> str:
    devices = []
    for device in state["devices"]:
        item = {
            "type": device["type"],
            "pin": int(device["pin"]),
            "elapsed_t": int(device["current_t"]),
            "reschedule": 1 if int(device["reschedule"]) else 0,
            "pattern": device["pattern"],
        }
        if "id" in device:
            item["id"] = device["id"]
        devices.append(item)

    types = _device_types(devices)
    return _template("base.py.tmpl").format(
        provenance_block=_provenance_block(
            controller_id=controller_id,
            state={"report_every": int(state["report_every"]), "devices": state["devices"]},
            git_version=git_version,
            generated_at=generated_at,
            options=options,
        ),
        machine_import=_machine_import(types),
        loop_sleep_ms=options.loop_sleep_ms,
        report_every=int(state["report_every"]),
        pwm_helper=_render_pwm_helper(types, options.pwm_freq).rstrip(),
        device_assignments=_render_device_assignments(devices),
    ).rstrip() + "\n"
