from __future__ import annotations

import json


def generate_main_py(payload: dict) -> str:
    report_every = int(payload.get("report_every", 5))
    if report_every <= 0:
        report_every = 5
    message = str(payload.get("message", "hello from pico_doser"))

    provenance = {
        "report_every": report_every,
        "message": message,
    }

    return (
        '"""\n'
        "Generated by: plamp/pico-firmware/pico_doser_generator.py\n"
        "Generated at: local-cli\n"
        "Git version: local-cli\n"
        "Generator input:\n"
        f"{json.dumps(provenance, indent=2)}\n"
        '"""\n\n'
        "import time\n"
        "import ujson as json\n\n"
        f"REPORT_EVERY = {report_every}\n"
        f"MESSAGE = {json.dumps(message)}\n\n"
        "def report():\n"
        '    print(json.dumps({"type": "report", "content": {"message": MESSAGE}}))\n\n'
        "def main():\n"
        "    while True:\n"
        "        report()\n"
        "        time.sleep(REPORT_EVERY)\n\n"
        'if __name__ == "__main__":\n'
        "    main()\n"
    )
